<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.42.3 (20191010.1750)
 -->
<!-- Title: snakemake_dag Pages: 1 -->
<svg width="364pt" height="337pt"
 viewBox="0.00 0.00 364.00 337.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 333)">
<title>snakemake_dag</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-333 360,-333 360,4 -4,4"/>
<!-- 0 -->
<g id="node1" class="node">
<title>0</title>
<path fill="none" stroke="#d85656" stroke-width="2" stroke-dasharray="5,2" d="M192,-36C192,-36 162,-36 162,-36 156,-36 150,-30 150,-24 150,-24 150,-12 150,-12 150,-6 156,0 162,0 162,0 192,0 192,0 198,0 204,-6 204,-12 204,-12 204,-24 204,-24 204,-30 198,-36 192,-36"/>
<text text-anchor="middle" x="177" y="-15.5" font-family="sans" font-size="10.00">all</text>
</g>
<!-- 1 -->
<g id="node2" class="node">
<title>1</title>
<path fill="none" stroke="#d8a456" stroke-width="2" stroke-dasharray="5,2" d="M159,-108C159,-108 119,-108 119,-108 113,-108 107,-102 107,-96 107,-96 107,-84 107,-84 107,-78 113,-72 119,-72 119,-72 159,-72 159,-72 165,-72 171,-78 171,-84 171,-84 171,-96 171,-96 171,-102 165,-108 159,-108"/>
<text text-anchor="middle" x="139" y="-87.5" font-family="sans" font-size="10.00">amrfinder</text>
</g>
<!-- 1&#45;&gt;0 -->
<g id="edge1" class="edge">
<title>1&#45;&gt;0</title>
<path fill="none" stroke="grey" stroke-width="2" d="M148.39,-71.7C152.76,-63.64 158.06,-53.89 162.9,-44.98"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="166.02,-46.56 167.71,-36.1 159.87,-43.22 166.02,-46.56"/>
</g>
<!-- 2 -->
<g id="node3" class="node">
<title>2</title>
<path fill="none" stroke="#56a2d8" stroke-width="2" stroke-dasharray="5,2" d="M151,-180C151,-180 119,-180 119,-180 113,-180 107,-174 107,-168 107,-168 107,-156 107,-156 107,-150 113,-144 119,-144 119,-144 151,-144 151,-144 157,-144 163,-150 163,-156 163,-156 163,-168 163,-168 163,-174 157,-180 151,-180"/>
<text text-anchor="middle" x="135" y="-159.5" font-family="sans" font-size="10.00">plasmid</text>
</g>
<!-- 2&#45;&gt;1 -->
<g id="edge3" class="edge">
<title>2&#45;&gt;1</title>
<path fill="none" stroke="grey" stroke-width="2" d="M135.99,-143.7C136.43,-135.98 136.96,-126.71 137.45,-118.11"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="140.95,-118.29 138.02,-108.1 133.96,-117.89 140.95,-118.29"/>
</g>
<!-- 6 -->
<g id="node7" class="node">
<title>6</title>
<path fill="none" stroke="#78d856" stroke-width="2" stroke-dasharray="5,2" d="M231,-108C231,-108 201,-108 201,-108 195,-108 189,-102 189,-96 189,-96 189,-84 189,-84 189,-78 195,-72 201,-72 201,-72 231,-72 231,-72 237,-72 243,-78 243,-84 243,-84 243,-96 243,-96 243,-102 237,-108 231,-108"/>
<text text-anchor="middle" x="216" y="-87.5" font-family="sans" font-size="10.00">prokka</text>
</g>
<!-- 2&#45;&gt;6 -->
<g id="edge8" class="edge">
<title>2&#45;&gt;6</title>
<path fill="none" stroke="grey" stroke-width="2" d="M155.02,-143.7C165.13,-134.97 177.54,-124.24 188.52,-114.75"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="190.93,-117.29 196.21,-108.1 186.35,-111.99 190.93,-117.29"/>
</g>
<!-- 3 -->
<g id="node4" class="node">
<title>3</title>
<path fill="none" stroke="#c6d856" stroke-width="2" stroke-dasharray="5,2" d="M200.5,-252C200.5,-252 155.5,-252 155.5,-252 149.5,-252 143.5,-246 143.5,-240 143.5,-240 143.5,-228 143.5,-228 143.5,-222 149.5,-216 155.5,-216 155.5,-216 200.5,-216 200.5,-216 206.5,-216 212.5,-222 212.5,-228 212.5,-228 212.5,-240 212.5,-240 212.5,-246 206.5,-252 200.5,-252"/>
<text text-anchor="middle" x="178" y="-231.5" font-family="sans" font-size="10.00">polish_flye</text>
</g>
<!-- 3&#45;&gt;2 -->
<g id="edge5" class="edge">
<title>3&#45;&gt;2</title>
<path fill="none" stroke="grey" stroke-width="2" d="M167.37,-215.7C162.37,-207.56 156.31,-197.69 150.79,-188.7"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="153.72,-186.79 145.51,-180.1 147.76,-190.46 153.72,-186.79"/>
</g>
<!-- 5 -->
<g id="node6" class="node">
<title>5</title>
<path fill="none" stroke="#56d87b" stroke-width="2" stroke-dasharray="5,2" d="M249,-180C249,-180 193,-180 193,-180 187,-180 181,-174 181,-168 181,-168 181,-156 181,-156 181,-150 187,-144 193,-144 193,-144 249,-144 249,-144 255,-144 261,-150 261,-156 261,-156 261,-168 261,-168 261,-174 255,-180 249,-180"/>
<text text-anchor="middle" x="221" y="-159.5" font-family="sans" font-size="10.00">chromosome</text>
</g>
<!-- 3&#45;&gt;5 -->
<g id="edge7" class="edge">
<title>3&#45;&gt;5</title>
<path fill="none" stroke="grey" stroke-width="2" d="M188.63,-215.7C193.63,-207.56 199.69,-197.69 205.21,-188.7"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="208.24,-190.46 210.49,-180.1 202.28,-186.79 208.24,-190.46"/>
</g>
<!-- 4 -->
<g id="node5" class="node">
<title>4</title>
<path fill="none" stroke="#56d8c9" stroke-width="2" stroke-dasharray="5,2" d="M344,-329C344,-329 12,-329 12,-329 6,-329 0,-323 0,-317 0,-317 0,-300 0,-300 0,-294 6,-288 12,-288 12,-288 344,-288 344,-288 350,-288 356,-294 356,-300 356,-300 356,-317 356,-317 356,-323 350,-329 344,-329"/>
<text text-anchor="middle" x="178" y="-317" font-family="sans" font-size="10.00">denovo</text>
<text text-anchor="middle" x="178" y="-306" font-family="sans" font-size="10.00">res: /home/ubuntu/data/belson/isangi_nanopore/qc/results/2021.03.08</text>
<text text-anchor="middle" x="178" y="-295" font-family="sans" font-size="10.00">sample: CHF10J</text>
</g>
<!-- 4&#45;&gt;3 -->
<g id="edge6" class="edge">
<title>4&#45;&gt;3</title>
<path fill="none" stroke="grey" stroke-width="2" d="M178,-287.69C178,-279.91 178,-270.84 178,-262.45"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="181.5,-262.32 178,-252.32 174.5,-262.32 181.5,-262.32"/>
</g>
<!-- 5&#45;&gt;1 -->
<g id="edge4" class="edge">
<title>5&#45;&gt;1</title>
<path fill="none" stroke="grey" stroke-width="2" d="M200.73,-143.7C190.5,-134.97 177.94,-124.24 166.82,-114.75"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="168.91,-111.94 159.04,-108.1 164.37,-117.26 168.91,-111.94"/>
</g>
<!-- 5&#45;&gt;6 -->
<g id="edge9" class="edge">
<title>5&#45;&gt;6</title>
<path fill="none" stroke="grey" stroke-width="2" d="M219.76,-143.7C219.21,-135.98 218.55,-126.71 217.94,-118.11"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="221.43,-117.83 217.22,-108.1 214.44,-118.33 221.43,-117.83"/>
</g>
<!-- 6&#45;&gt;0 -->
<g id="edge2" class="edge">
<title>6&#45;&gt;0</title>
<path fill="none" stroke="grey" stroke-width="2" d="M206.36,-71.7C201.87,-63.64 196.44,-53.89 191.48,-44.98"/>
<polygon fill="grey" stroke="grey" stroke-width="2" points="194.45,-43.14 186.53,-36.1 188.34,-46.54 194.45,-43.14"/>
</g>
</g>
</svg>
