1_Acinetobacter_baumannii_J9:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Acinetobacter_baumannii_J9/Acinetobacter_baumannii_J9_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Acinetobacter_baumannii_J9/Acinetobacter_baumannii_J9_R2.fastq.gz
2_Citrobacter_koseri_MINF_9D:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Citrobacter_koseri_MINF_9D/Citrobacter_koseri_MINF_9D_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Citrobacter_koseri_MINF_9D/Citrobacter_koseri_MINF_9D_R2.fastq.gz
3_Enterobacter_kobei_MSB1_1B:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Enterobacter_kobei_MSB1_1B/Enterobacter_kobei_MSB1_1B_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Enterobacter_kobei_MSB1_1B/Enterobacter_kobei_MSB1_1B_R2.fastq.gz
4_Haemophilus_unknown_M1C132_1:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Haemophilus_unknown_M1C132_1/Haemophilus_unknown_M1C132_1_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Haemophilus_unknown_M1C132_1/Haemophilus_unknown_M1C132_1_R2.fastq.gz
5_Klebsiella_oxytoca_MSB1_2C:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Klebsiella_oxytoca_MSB1_2C/Klebsiella_oxytoca_MSB1_2C_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Klebsiella_oxytoca_MSB1_2C/Klebsiella_oxytoca_MSB1_2C_R2.fastq.gz
7_Klebsiella_variicola_INF345:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Klebsiella_variicola_INF345/Klebsiella_variicola_INF345_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Klebsiella_variicola_INF345/Klebsiella_variicola_INF345_R2.fastq.gz
8_Serratia_marcescens_17-147-1671:
  R1:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Serratia_marcescens_17-147-1671/Serratia_marcescens_17-147-1671_R1.fastq.gz
  R2:
    /home/ubuntu/data/phil/monash_data/clean_illumina_reads/Serratia_marcescens_17-147-1671/Serratia_marcescens_17-147-1671_R2.fastq.gz
